import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Page from '../components/Page'
import Head from 'next/head'

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <Page>
       <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<Component {...pageProps} />
</Page>
  )
}

export default MyApp
